# Generated by Django 5.0.3 on 2024-03-28 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='receipt',
            field=models.FileField(default='default.png', upload_to='payement_receipts'),
        ),
    ]
